name: build-cmake-redesign

on:
  push:
    branches:
      - cmake-redesign
  workflow_dispatch:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-win-SDL:
    runs-on: [windows-latest]
    env:
      SDL2_URL: "https://www.libsdl.org/release/SDL2-devel-2.0.22-VC.zip"
      SDL2_TTF_URL: "https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-VC.zip"
      SDL2_PATH: "C:\\SDL"
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install requests
      run: pip install requests
    - name: Install SDL2
      run: python .github/workflows/win_sdl2.py
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="C:\SDL\SDL2-2.0.22;C:\SDL\SDL2_ttf-2.0.15"
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Add tag data to enviroment
      run: |
        $output=$(python .github/workflows/get_version.py AppCUI/include/AppCUI.hpp)
        echo "APPCUI_VERSION=$output" | Out-File -FilePath $env:GITHUB_ENV -Append
    
    - name: Create archive SDL
      run: |
        $output=$(7z a "AppCUI-SDL-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" C:/SDL/SDL2-2.0.22/lib/x64/*.dll)
        echo "$output"
        $output=$(7z a "AppCUI-SDL-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" C:/SDL/SDL2_ttf-2.0.15/lib/x64/*.dll)
        echo "$output"

        $output=$(7z a "AppCUI-SDL-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" D:/a/AppCUI/AppCUI/bin/Release/*.exe)
        echo "$output"
        $output=$(7z a "AppCUI-SDL-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" D:/a/AppCUI/AppCUI/bin/Release/*.dll)
        echo "$output"
    
    - name: Store Artifacts SDL
      uses: actions/upload-artifact@v3
      with:
        name: windows_artifacts_sdl
        path: "AppCUI-SDL-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip"
        retention-days: 1

  build-win:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    
    - name: Add tag data to enviroment
      run: |
        $output=$(python .github/workflows/get_version.py AppCUI/include/AppCUI.hpp)
        echo "APPCUI_VERSION=$output" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Create archive
      run: |
        $output=$(7z a "AppCUI-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" D:/a/AppCUI/AppCUI/bin/Release/*.exe)
        echo "$output"
        $output=$(7z a "AppCUI-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" D:/a/AppCUI/AppCUI/bin/Release/*.dll)
        echo "$output"
    
    - name: Store Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows_artifacts
        path: "AppCUI-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip"
        retention-days: 1

  build-ubuntu-SDL:
    runs-on: [ubuntu-latest]
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Update
      run: sudo apt-get update -y
    - name: Install SDL2
      run: sudo apt-get install libsdl2-dev -y
    - name: Install SDL2ttf
      run: sudo apt-get install libsdl2-ttf-dev -y
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Add tag data to enviroment
      run: |
        output=$(python .github/workflows/get_version.py AppCUI/include/AppCUI.hpp)
        echo "APPCUI_VERSION=$output" >> $GITHUB_ENV

    - name: Create archive SDL
      working-directory: /home/runner/work/AppCUI/AppCUI/bin
      run: |
        output=$(zip -9 -r "AppCUI-SDL-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" .)
        echo "$output"
    
    - name: Store Artifacts SDL
      uses: actions/upload-artifact@v3
      with:
        name: linux_artifacts_sdl
        path: "/home/runner/work/AppCUI/AppCUI/bin/AppCUI-SDL-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip"
        retention-days: 1  

  build-ubuntu:
    runs-on: [ubuntu-latest]
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Update
      run: sudo apt-get update -y
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Add tag data to enviroment
      run: |
        output=$(python .github/workflows/get_version.py AppCUI/include/AppCUI.hpp)
        echo "APPCUI_VERSION=$output" >> $GITHUB_ENV

    - name: Create archive
      working-directory: /home/runner/work/AppCUI/AppCUI/bin
      run: |
        output=$(zip -9 -r "AppCUI-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" .)
        echo "$output"
    
    - name: Store Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux_artifacts
        path: "/home/runner/work/AppCUI/AppCUI/bin/AppCUI-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip"
        retention-days: 1  

  build-osx-SDL:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Brew prefix
      run: brew --prefix
    
    - name: Install brew sdl2
      run: brew install sdl2

    - name: SDL2 Cellar
      run: brew --cellar sdl2
      
    - name: SDL2 Prefix
      run: brew --prefix sdl2
    
    - name: Install brew sdl2_ttf
      run: brew install sdl2_ttf

    - name: SDL2 TTF Cellar
      run: brew --cellar sdl2_ttf
      
    - name: SDL2 TTF Prefix
      run: brew --prefix sdl2_ttf

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Add tag data to enviroment
      run: |
        output=$(python .github/workflows/get_version.py AppCUI/include/AppCUI.hpp)
        echo "APPCUI_VERSION=$output" >> $GITHUB_ENV

    - name: Create archive SDL
      working-directory: /Users/runner/work/AppCUI/AppCUI/bin
      run: |
        output=$(zip -9 -r "AppCUI-SDL-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" .)
        echo "$output"
    
    - name: Store Artifacts SDL
      uses: actions/upload-artifact@v3
      with:
        name: apple_artifacts_sdl
        path: "/Users/runner/work/AppCUI/AppCUI/bin/AppCUI-SDL-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip"
        retention-days: 1  

  build-osx:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Brew prefix
      run: brew --prefix
    
    - name: Install brew ncurses
      run: brew install ncurses

    - name: NCurses Cellar
      run: brew --cellar ncurses
      
    - name: NCurses Prefix
      run: brew --prefix ncurses
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Add tag data to enviroment
      run: |
        output=$(python .github/workflows/get_version.py AppCUI/include/AppCUI.hpp)
        echo "APPCUI_VERSION=$output" >> $GITHUB_ENV

    - name: Create archive
      working-directory: /Users/runner/work/AppCUI/AppCUI/bin
      run: |
        output=$(zip -9 -r "AppCUI-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip" .)
        echo "$output"
    
    - name: Store Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: apple_artifacts
        path: "/Users/runner/work/AppCUI/AppCUI/bin/AppCUI-${{ runner.os }}-${{ runner.arch }}-${{ env.APPCUI_VERSION }}.zip"
        retention-days: 1  

  publish_job:
    name: "Publish to release"
    runs-on: [ubuntu-latest]
    needs: [build-win-SDL, build-win, build-ubuntu-SDL, build-ubuntu, build-osx-SDL, build-osx]
    steps:
    - uses: actions/checkout@v2

    - name: Add tag data to enviroment
      run: |
        output=$(python .github/workflows/get_version.py AppCUI/include/AppCUI.hpp)
        echo "APPCUI_VERSION=$output" >> $GITHUB_ENV

    - uses: actions/download-artifact@v2
      with:
        name: windows_artifacts_sdl
        path: artifacts

    - uses: actions/download-artifact@v2
      with:
        name: windows_artifacts
        path: artifacts

    - uses: actions/download-artifact@v2
      with:
        name: linux_artifacts_sdl
        path: artifacts

    - uses: actions/download-artifact@v2
      with:
        name: linux_artifacts
        path: artifacts

    - uses: actions/download-artifact@v2
      with:
        name: apple_artifacts_sdl
        path: artifacts

    - uses: actions/download-artifact@v2
      with:
        name: apple_artifacts
        path: artifacts

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{env.APPCUI_VERSION}}"
        prerelease: true # ${{ github.event.inputs.isPreRelease }}
        title: Build ${{env.APPCUI_VERSION}}
        files: |
            artifacts/*.zip